---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - azurepipelines.k8s.scaler.io
  resources:
  - autoscaledagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azurepipelines.k8s.scaler.io
  resources:
  - autoscaledagents/finalizers
  verbs:
  - update
- apiGroups:
  - azurepipelines.k8s.scaler.io
  resources:
  - autoscaledagents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
