apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: azure-pipelines-k8s-agent-scaler
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
