apiVersion: azurepipelines.k8s.scaler.io/v1
kind: AutoScaledAgent
metadata:
  labels:
    app.kubernetes.io/name: autoscaledagent
    app.kubernetes.io/instance: autoscaledagent-sample
    app.kubernetes.io/part-of: azure-pipelines-k8s-agent-scaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: azure-pipelines-k8s-agent-scaler
  name: autoscaledagent-sample
spec:
  # TODO(user): Add fields here
