apiVersion: azurepipelines.k8s.scaler.io/v1
kind: AutoScaledAgent
metadata:
  labels:
    app.kubernetes.io/name: azure-pipelines-k8s-agent-scaler
    app.kubernetes.io/managed-by: kustomize
  name: autoscaledagent-sample
spec:
  # TODO(user): Add fields here
