apiVersion: azurepipelines.k8s.scaler.io/v1
kind: AutoScaledAgent
metadata:
  labels:
    app.kubernetes.io/name: autoscaledagent
    app.kubernetes.io/instance: autoscaledagent-sample
    app.kubernetes.io/part-of: azure-pipelines-k8s-agent-scaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: azure-pipelines-k8s-agent-scaler
  name: autoscaledagent-sample
spec:
  poolName: shark-agents-vm-npi
  organizationUrl: https://dev.azure.com/test
  personalAccessTokenSecretName: azure-pat
  podsWithCapabilities:
    - capabilities:
        foo: bar
      minCount: 0
      maxCount: 1
      podTemplateSpec:
#        metadata:
#          labels:
#            hallo: welt
        spec:
          containers:
            - name: nginx
              image: nginx:1.14.2
