apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "demo-agent.labels" . | nindent 4 }}
  name: buildkit-config
data:
  buildkitd.toml: |
    {{- if .Values.buildkitConfig.debug }}
    debug = true
    {{- end }}

    [worker]

    [worker.containerd]
      enabled = false

    [worker.oci]
      enabled = true
      gc = true

      [[worker.oci.gcpolicy]]
        filters = ["type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
        keepBytes = {{ mul 1073741824 .Values.buildkitConfig.gc.keepCacheMountsGi }}

      [[worker.oci.gcpolicy]]
        all = true
        keepBytes = {{ mul 1073741824 .Values.buildkitConfig.gc.keepTotalGi }}
