kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-interpod-com
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
