apiVersion: v1
kind: Pod
metadata:
  name: test-fake-agent
spec:
  containers:
    - name: fake-agent
      image: foo-registry:5000/fake-agent:local
      env:
        - name: AZP_URL
          value: http://srv:80
        - name: AZP_POOL
          value: Default
        - name: AZP_AGENT_NAME
          value: hello-world

